//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocation
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
