//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIUM
    {
        public string AUDITORIUM1 { get; set; }
        public string AUDITORIUM_NAME { get; set; }
        public Nullable<int> AUDITORIUM_CAPACITY { get; set; }
        public string AUDITORIUM_TYPE { get; set; }
    
        public virtual AUDITORIUM_TYPE AUDITORIUM_TYPE1 { get; set; }
    }
}
