//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PulpitsOnFaculty
    {
        public string FACULTY { get; set; }
        public string FACULTY_NAME { get; set; }
        public string PULPIT_NAME { get; set; }
    }
}
