//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PULPIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PULPIT()
        {
            this.SUBJECT = new HashSet<SUBJECT>();
            this.TEACHER = new HashSet<TEACHER>();
        }
    
        public string PULPIT1 { get; set; }
        public string PULPIT_NAME { get; set; }
        public string FACULTY { get; set; }
    
        public virtual FACULTY FACULTY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT> SUBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER> TEACHER { get; set; }
    }
}
