//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.STUDENT_MARK = new HashSet<STUDENT_MARK>();
        }
    
        public string STUDENT1 { get; set; }
        public string STUDENT_NAME { get; set; }
        public string FACULTY { get; set; }
        public string PHONE_NUMBER { get; set; }
        public System.Data.Entity.Spatial.DbGeography HOME_ADDRESS { get; set; }
    
        public virtual FACULTY FACULTY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_MARK> STUDENT_MARK { get; set; }
    }
}
