//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_MARK
    {
        public string STUDENT { get; set; }
        public string SUBJECT { get; set; }
        public int MARK { get; set; }
    
        public virtual STUDENT STUDENT1 { get; set; }
        public virtual SUBJECT SUBJECT1 { get; set; }
    }
}
