//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersSubjects
    {
        public string TEACHER { get; set; }
        public string TEACHER_NAME { get; set; }
        public string SUBJECT_NAME { get; set; }
    }
}
