select * from users;
select * from post;
select * from likes;
select * from comments;
select * from messages;
select * from friendships;


drop table likes;
drop table comments;
drop table messages;
drop table friendships;
drop table post;
drop table users;


drop table report;

CREATE TABLE Users (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR2(50),
last_name VARCHAR2(50),
email VARCHAR2(100),
PRIMARY KEY (id)
);

CREATE TABLE Post (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
user_id NUMBER,
post_text VARCHAR2(100),
post_date TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES Users(id),
PRIMARY KEY (id)
);

CREATE TABLE Comments (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
post_id NUMBER,
user_id NUMBER,
comment_text VARCHAR2(100),
comment_date TIMESTAMP,
FOREIGN KEY (post_id) REFERENCES Post(id),
FOREIGN KEY (user_id) REFERENCES Users(id),
PRIMARY KEY (id)
);

CREATE TABLE Likes (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
post_id NUMBER,
user_id NUMBER,
like_date TIMESTAMP,
FOREIGN KEY (post_id) REFERENCES Post(id),
FOREIGN KEY (user_id) REFERENCES Users(id),
PRIMARY KEY (id)
);

CREATE TABLE Friendships (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
user_id_1 NUMBER,
user_id_2 NUMBER,
friendship_date TIMESTAMP,
FOREIGN KEY (user_id_1) REFERENCES Users(id),
FOREIGN KEY (user_id_2) REFERENCES Users(id),
PRIMARY KEY (id)
);

CREATE TABLE Messages (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
SenderId NUMBER,
ReceiverId NUMBER,
message_text VARCHAR2(100),
message_date TIMESTAMP,
FOREIGN KEY (SenderId) REFERENCES Users(id),
FOREIGN KEY (ReceiverId) REFERENCES Users(id),
PRIMARY KEY (id)
);

-- Заполнение таблицы Users
INSERT INTO Users (first_name, last_name, email)
VALUES ('John', 'Doe', 'johndoe@example.com');

INSERT INTO Users (first_name, last_name, email)
VALUES ('Jane', 'Smith', 'janesmith@example.com');

-- Заполнение таблицы Post
INSERT INTO Post (user_id, post_text, post_date)
VALUES (1, 'Hello, world!', TIMESTAMP '2023-05-30 10:00:00');

INSERT INTO Post (user_id, post_text, post_date)
VALUES (2, 'I love coding!', TIMESTAMP '2023-05-31 14:30:00');

-- Заполнение таблицы Comment
INSERT INTO Comments (post_id, user_id, comment_text, comment_date)
VALUES (1, 2, 'Nice post!', TIMESTAMP '2023-05-30 11:30:00');

INSERT INTO Comments (post_id, user_id, comment_text, comment_date)
VALUES (2, 1, 'Great passion for coding!', TIMESTAMP '2023-05-31 15:00:00');

-- Заполнение таблицы Likes
INSERT INTO Likes (post_id, user_id, like_date)
VALUES (1, 2, TIMESTAMP '2023-05-30 11:45:00');

INSERT INTO Likes (post_id, user_id, like_date)
VALUES (2, 1, TIMESTAMP '2023-05-31 15:10:00');

-- Заполнение таблицы Friendships
INSERT INTO Friendships (user_id_1, user_id_2, friendship_date)
VALUES (1, 2, TIMESTAMP '2023-05-30 12:00:00');

INSERT INTO Friendships (user_id_1, user_id_2, friendship_date)
VALUES (2, 1, TIMESTAMP '2023-05-31 16:00:00');

-- Заполнение таблицы Messages
INSERT INTO Messages (SenderId, ReceiverId, message_text, message_date)
VALUES (1, 2, 'Hello Jane! How are you?', TIMESTAMP '2023-05-30 12:30:00');

INSERT INTO Messages (SenderId, ReceiverId, message_text, message_date)
VALUES (2, 1, 'Hi John! I am doing great, thanks!', TIMESTAMP '2023-05-31 16:30:00');